<a href="https://colab.research.google.com/github/Hritikrai55/CSAT-ANN-Project/blob/main/CSAT_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Overview of Project**
This project focuses on predicting Customer Satisfaction (CSAT) scores using Deep Learning Artificial Neural Networks (ANN). In the context of e-commerce, understanding customer satisfaction through their interactions and feedback is crucial for enhancing service quality, customer retention, and overall business growth. By leveraging advanced neural network models, we aim to accurately forecast CSAT scores based on a myriad of interaction-related features, providing actionable insights for service improvement.

## About Dataset
The dataset captures customer satisfaction scores for a one-month period at an e-commerce platform called Shopzilla (a pseudonym). It includes various features such as category and sub-category of interaction, customer remarks, survey response date, category, item price, agent details (name, supervisor, manager), and CSAT score etc.

## **Project Background**
Customer satisfaction in the e-commerce sector is a pivotal metric that influences loyalty, repeat business, and word-of-mouth marketing. Traditionally, companies have relied on direct surveys to gauge customer satisfaction, which can be time-consuming and may not always capture the full spectrum of customer experiences. With the advent of deep learning, it's now possible to predict customer satisfaction scores in real-time, offering a granular view of service performance and identifying areas for immediate improvement.

## Data Description:

Unique id:	Unique identifier for each record

Channel name:	Name of the customer service channel

Category:	Category of the interaction

Sub-category:	Sub-category of the interaction

Customer Remarks:	Feedback provided by the customer

Order id:	Identifier for the order associated with the interaction

Order date time:	Date and time of the order

Issue reported at:	Timestamp when the issue was reported

Issue responded:	Timestamp when the issue was responded to

Survey response date:	Date of the customer survey response

Customer city:	City of the customer

Product category:	Category of the product

Item price:	Price of the item

Connected handling time:	Time taken to handle the interaction

Agent name:	Name of the customer service agent

Supervisor:	Name of the supervisor

Manager:	Name of the manager

Tenure Bucket:	Bucket categorizing agent tenure

Agent Shift:	Shift timing of the agent

CSAT Score:	Customer Satisfaction (CSAT) score

## **Project Goal**
The primary goal of this project is to develop a deep learning model that can accurately predict the CSAT scores based on customer interactions and feedback. By doing so, we aim to provide e-commerce businesses with a powerful tool to monitor and enhance customer satisfaction in real-time, thereby improving service quality and fostering customer loyalty.

In [ ]:
#Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
import zipfile

from sklearn.preprocessing import FunctionTransformer
import scipy.stats as stats

In [ ]:
#Extract, read data and Create data frame
df=pd.read_csv('eCommerce_Customer_support_data.csv')

In [ ]:
df.head()

,Unique id,channel_name,category,Sub-category,Customer Remarks,Order_id,order_date_time,Issue_reported at,issue_responded,Survey_response_Date,Customer_City,Product_category,Item_price,connected_handling_time,Agent_name,Supervisor,Manager,Tenure Bucket,Agent Shift,CSAT Score
0,7e9ae164-6a8b-4521-a2d4-58f7c9fff13f,Outcall,Product Queries,Life Insurance,NaN,c27c9bb4-fa36-4140-9f1f-21009254ffdb,NaN,01/08/2023 11:13,01/08/2023 11:47,01-Aug-23,NaN,NaN,NaN,NaN,Richard Buchanan,Mason Gupta,Jennifer Nguyen,On Job Training,Morning,5
1,b07ec1b0-f376-43b6-86df-ec03da3b2e16,Outcall,Product Queries,Product Specific Information,NaN,d406b0c7-ce17-4654-b9de-f08d421254bd,NaN,01/08/2023 12:52,01/08/2023 12:54,01-Aug-23,NaN,NaN,NaN,NaN,Vicki Collins,Dylan Kim,Michael Lee,>90,Morning,5
2,200814dd-27c7-4149-ba2b-bd3af3092880,Inbound,Order Related,Installation/demo,NaN,c273368d-b961-44cb-beaf-62d6fd6c00d5,NaN,01/08/2023 20:16,01/08/2023 20:38,01-Aug-23,NaN,NaN,NaN,NaN,Duane Norman,Jackson Park,William Kim,On Job Training,Evening,5
3,eb0d3e53-c1ca-42d3-8486-e42c8d622135,Inbound,Returns,Reverse Pickup Enquiry,NaN,5aed0059-55a4-4ec6-bb54-97942092020a,NaN,01/08/2023 20:56,01/08/2023 21:16,01-Aug-23,NaN,NaN,NaN,NaN,Patrick Flores,Olivia Wang,John Smith,>90,Evening,5
4,ba903143-1e54-406c-b969-46c52f92e5df,Inbound,Cancellation,Not Needed,NaN,e8bed5a9-6933-4aff-9dc6-ccefd7dcde59,NaN,01/08/2023 10:30,01/08/2023 10:32,01-Aug-23,NaN,NaN,NaN,NaN,Christopher Sanchez,Austin Johnson,Michael Lee,0-30,Morning,5

In [ ]:
print("This data set has",df.shape[0],"rows and",df.shape[1],"columns.")

This data set has 85907 rows and 20 columns.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85907 entries, 0 to 85906
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unique id                85907 non-null  object
 1   channel_name             85907 non-null  object
 2   category                 85907 non-null  object
 3   Sub-category             85907 non-null  object
 4   Customer Remarks         28742 non-null  object
 5   Order_id                 67675 non-null  object
 6   order_date_time          17214 non-null  object
 7   Issue_reported at        85907 non-null  object
 8   issue_responded          85907 non-null  object
 9   Survey_response_Date     85907 non-null  object
 10  Customer_City            17079 non-null  object
 11  Product_category         17196 non-null  object
 12  Item_price               17206 non-null  float64
 13  connected_handling_time  242 non-null    float64
 14  Agent_name               85907 non-null  object
 15  Supervisor               85907 non-null  object
 16  Manager                  85907 non-null  object
 17  Tenure Bucket            85907 non-null  object
 18  Agent Shift              85907 non-null  object
 19  CSAT Score               85907 non-null  int64
dtypes: float64(2), int64(1), object(17)
memory usage: 13.1+ MB

Based on data set info. This df has dumped with 85907 rows and 20 Columns.

Except 3 variable such as (Item_price, Connected_handling_time and CSAT Score) all other variables seems to be Object data type.

The data shows like non-null but as per count in some variable, many data might be fill with NAN, NA or some other charecters.

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Item_price,17206.0,5660.774846,12825.728411,0.0,392.0,979.0,2699.75,164999.0
connected_handling_time,242.0,462.400826,246.295037,0.0,293.0,427.0,592.25,1986.0
CSAT Score,85907.0,4.242157,1.378903,1.0,4.0,5.0,5.00,5.0

Describe is actually an 5 point summary which will calculate for numerical values. So the reason only 3 variable got described.

* Item_price and connected_handling_time has its bell shape curve with a huge left skewness and these both seems to have too many outlier.

* CSAT variable has numerical Dtype but it looks like a categorical variable.

In [ ]:
for i in df.columns:
    print(df[i].value_counts())

Unique id
07c7a878-0d5a-42e0-97ef-de59abec0238    1
7e9ae164-6a8b-4521-a2d4-58f7c9fff13f    1
b07ec1b0-f376-43b6-86df-ec03da3b2e16    1
c0d72065-e4c8-449b-9d55-cadb690b9c54    1
49e1675a-e890-4d27-93a0-51e67a44d86a    1
                                       ..
372b51a5-fa19-4a31-a4b8-a21de117d75e    1
11a3ffd8-1d6b-4806-b198-c60b5934c9bc    1
1cfde5b9-6112-44fc-8f3b-892196137a62    1
ba903143-1e54-406c-b969-46c52f92e5df    1
eb0d3e53-c1ca-42d3-8486-e42c8d622135    1
Name: count, Length: 85907, dtype: int64
channel_name
Inbound    68142
Outcall    14742
Email       3023
Name: count, dtype: int64
category
Returns               44097
Order Related         23215
Refund Related         4550
Product Queries        3692
Shopzilla Related      2792
Payments related       2327
Feedback               2294
Cancellation           2212
Offers & Cashback       480
Others                   99
App/website              84
Onboarding related       65
Name: count, dtype: int64
Sub-category
Reverse Pickup Enquiry              22389
Return request                       8523
Delayed                              7388
Order status enquiry                 6922
Installation/demo                    4116
Fraudulent User                      4108
Product Specific Information         3589
Refund Enquiry                       2665
Wrong                                2597
Missing                              2556
UnProfessional Behaviour             2294
General Enquiry                      1945
Not Needed                           1920
Service Centres Related              1875
Refund Related Issues                1800
Invoice request                      1465
Online Payment Issues                1079
Seller Cancelled Order               1059
Priority delivery                     972
Exchange / Replacement                896
Customer Requested Modifications      805
Payment related Queries               743
Signup Issues                         489
Damaged                               475
Technician Visit                      378
Shopzila Premium Related              361
Return cancellation                   292
Wallet related                        230
Other Cashback                        219
Product related Issues                183
Affiliate Offers                      183
Unable to track                       164
Account updation                      150
PayLater related                      140
COD Refund Details                     85
Shopzilla Rewards                      80
Instant discount                       78
Warranty related                       78
Issues with Shopzilla App              74
Order Verification                     72
Seller onboarding                      62
Service Center - Service Denial        58
Billing Related                        57
Self-Help                              49
Call back request                      46
e-Gift Voucher                         42
Call disconnected                      40
Life Insurance                         23
Other Account Related Issues           22
Card/EMI                               19
Payment pending                        17
Others                                 12
App/website Related                    10
Unable to Login                         7
Commission related                      3
Policy Related                          2
Non Order related                       1
Name: count, dtype: int64
Customer Remarks
Good                                                                                                                                                                                                                                         1390
Good                                                                                                                                                                                                                                         1158
Very good                                                                                                                                                                                                                                     569
Nice                                                                                                                                                                                                                                          316
Thanks                                                                                                                                                                                                                                        276
                                                                                                                                                                                                                                             ...
Please add option to delete order history                                                                                                                                                                                                       1
Me                                                                                                                                                                                                                                              1
Delivery person call back received                                                                                                                                                                                                              1
Worst service and worst customer support executive. They even don\u2019t know what customer was asking about. Simply they will tell the given delivery date. No response for delaying the deliver. Please change the customer executives.       1
For Defect On Arrival scenario it is should be obvious return/replacement. I should not spend time talking to customer service agent for 15-20 mins!                                                                                            1
Name: count, Length: 18231, dtype: int64
Order_id
3230db30-f8da-4c44-8636-ec76d1d3d4f3    1
c27c9bb4-fa36-4140-9f1f-21009254ffdb    1
d406b0c7-ce17-4654-b9de-f08d421254bd    1
c273368d-b961-44cb-beaf-62d6fd6c00d5    1
5aed0059-55a4-4ec6-bb54-97942092020a    1
                                       ..
8153c646-4940-406f-992c-952ed08e9af8    1
9e0d7d55-d012-42f7-8e21-634942419386    1
c1e10375-7426-4b2a-aca6-17dc6bc9c7a3    1
c7d5eef8-d239-474c-8d24-542db2923b3c    1
55bbace3-eb2e-4f67-aacb-4f8ee8512f75    1
Name: count, Length: 67675, dtype: int64
order_date_time
09/08/2023 11:55    7
05/08/2023 20:14    6
08/08/2023 12:51    5
09/08/2023 21:56    5
05/08/2023 20:26    5
                   ..
22/08/2023 21:58    1
29/08/2023 12:28    1
26/07/2023 12:04    1
14/07/2023 22:09    1
20/07/2023 23:03    1
Name: count, Length: 13766, dtype: int64
Issue_reported at
13/08/2023 10:40    13
15/08/2023 10:59    13
06/08/2023 18:22    12
14/08/2023 12:08    12
11/08/2023 19:04    11
                    ..
31/08/2023 12:22     1
31/08/2023 11:20     1
31/08/2023 14:53     1
31/08/2023 03:06     1
31/08/2023 17:55     1
Name: count, Length: 30923, dtype: int64
issue_responded
28/08/2023 00:00    3378
27/08/2023 00:00      21
08/08/2023 17:51      13
17/08/2023 11:34      12
16/08/2023 13:24      12
                    ...
31/08/2023 20:19       1
31/08/2023 16:33       1
31/08/2023 10:58       1
31/08/2023 10:48       1
31/08/2023 20:52       1
Name: count, Length: 30262, dtype: int64
Survey_response_Date
28-Aug-23    3452
27-Aug-23    3379
17-Aug-23    3193
29-Aug-23    3188
07-Aug-23    3014
22-Aug-23    3005
08-Aug-23    3000
26-Aug-23    2990
10-Aug-23    2989
24-Aug-23    2962
23-Aug-23    2944
14-Aug-23    2927
11-Aug-23    2894
16-Aug-23    2885
12-Aug-23    2841
09-Aug-23    2823
15-Aug-23    2819
13-Aug-23    2758
30-Aug-23    2757
18-Aug-23    2605
25-Aug-23    2550
04-Aug-23    2523
21-Aug-23    2510
19-Aug-23    2496
06-Aug-23    2490
03-Aug-23    2467
31-Aug-23    2389
02-Aug-23    2330
05-Aug-23    2283
01-Aug-23    2231
20-Aug-23    2213
Name: count, dtype: int64
Customer_City
HYDERABAD    722
NEW DELHI    688
PUNE         435
MUMBAI       406
BANGALORE    352
            ...
NARAULI        1
AYOOR          1
MUL            1
HOWLI          1
FAIZPUR        1
Name: count, Length: 1782, dtype: int64
Product_category
Electronics                    4706
LifeStyle                      4118
Books & General merchandise    3323
Mobile                         1758
Home                           1328
Home Appliences                1300
Furniture                       471
Affiliates                      166
GiftCard                         26
Name: count, dtype: int64
Item_price
999.0      590
1499.0     326
899.0      309
1299.0     301
799.0      283
          ...
4974.0       1
4065.0       1
3674.0       1
1683.0       1
28500.0      1
Name: count, Length: 2789, dtype: int64
connected_handling_time
299.0    3
301.0    3
418.0    3
282.0    3
368.0    2
        ..
63.0     1
281.0    1
856.0    1
353.0    1
505.0    1
Name: count, Length: 211, dtype: int64
Agent_name
Wendy Taylor         429
Timothy Huff         265
David Smith          264
Jamie Smith          253
Kayla Wilson         216
                    ...
Jackson Brown         20
Alexis Murray         20
Matthew Ross          20
Stephanie Hammond     20
Amy Bell              20
Name: count, Length: 1371, dtype: int64
Supervisor
Carter Park         4273
Elijah Yamaguchi    3855
Zoe Yamamoto        3551
Nathan Patel        3549
Noah Patel          3434
Ava Wong            3373
Emma Park           3290
Mia Patel           3279
Evelyn Kimura       2974
Aiden Patel         2892
Madison Kim         2772
William Park        2692
Scarlett Chen       2676
Emily Yamashita     2581
Jackson Park        2571
Brayden Wong        2540
Logan Lee           2466
Olivia Wang         2233
Abigail Suzuki      2222
Olivia Suzuki       2193
Mason Gupta         2109
Lily Chen           1869
Ethan Tan           1831
Wyatt Kim           1727
Austin Johnson      1723
Sophia Sato         1671
Landon Tanaka       1635
Ethan Nakamura      1584
Jacob Sato          1501
Amelia Tanaka       1364
Alexander Tanaka    1320
Lucas Singh         1285
Dylan Kim           1197
Charlotte Suzuki    1172
Harper Wong         1119
Isabella Wong       1081
Layla Taniguchi      924
Mia Yamamoto         625
Oliver Nguyen        417
Sophia Chen          337
Name: count, dtype: int64
Manager
John Smith         25261
Michael Lee        17600
Jennifer Nguyen    15897
Emily Chen         14062
William Kim         8568
Olivia Tan          4519
Name: count, dtype: int64
Tenure Bucket
>90                30660
On Job Training    25523
31-60              11665
0-30               11318
61-90               6741
Name: count, dtype: int64
Agent Shift
Morning      41426
Evening      33677
Afternoon     5840
Split         3648
Night         1316
Name: count, dtype: int64
CSAT Score
5    59617
1    11230
4    11219
3     2558
2     1283
Name: count, dtype: int64

In [ ]:
#finding duplicate datas
df.duplicated().sum()

np.int64(0)

In [ ]:
# finding null values and unique value counts
null_values= round(df.isnull().sum() * 100 / len(df),2)
unique_values=df.nunique()
analysis_df = pd.DataFrame({'column_name': df.columns,"unique_values": unique_values,'null_values_%': null_values,"data_type":df.dtypes})
analysis_df.reset_index(drop=True,inplace=True)
analysis_df

                column_name  unique_values  null_values_% data_type
0                 Unique id          85907           0.00    object
1              channel_name              3           0.00    object
2                  category             12           0.00    object
3              Sub-category             57           0.00    object
4          Customer Remarks          18231          66.54    object
5                  Order_id          67675          21.22    object
6           order_date_time          13766          79.96    object
7         Issue_reported at          30923           0.00    object
8           issue_responded          30262           0.00    object
9      Survey_response_Date             31           0.00    object
10            Customer_City           1782          80.12    object
11         Product_category              9          79.98    object
12               Item_price           2789          79.97   float64
13  connected_handling_time            211          99.72   float64
14               Agent_name           1371           0.00    object
15               Supervisor             40           0.00    object
16                  Manager              6           0.00    object
17            Tenure Bucket              5           0.00    object
18              Agent Shift              5           0.00    object
19               CSAT Score              5           0.00     int64